name: update-reference
on: [workflow_dispatch]
jobs:
  update-reference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go run cmd/scrape-authref/scrape.go
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add service-auth.json
          git commit -m "New update to service-auth.json"
          git push
